package com.xuchen.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.departmentId
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private Integer departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.departmentName
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private String departmentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.managerName
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private String managername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.createDate
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.KPIFact
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private BigDecimal kpifact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.paidInAmount
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private BigDecimal paidinamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.departmentId
     *
     * @return the value of departments.departmentId
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.departmentId
     *
     * @param departmentid the value for departments.departmentId
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.departmentName
     *
     * @return the value of departments.departmentName
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.departmentName
     *
     * @param departmentname the value for departments.departmentName
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.managerName
     *
     * @return the value of departments.managerName
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.managerName
     *
     * @param managername the value for departments.managerName
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setManagername(String managername) {
        this.managername = managername == null ? null : managername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.createDate
     *
     * @return the value of departments.createDate
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.createDate
     *
     * @param createdate the value for departments.createDate
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.KPIFact
     *
     * @return the value of departments.KPIFact
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public BigDecimal getKpifact() {
        return kpifact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.KPIFact
     *
     * @param kpifact the value for departments.KPIFact
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setKpifact(BigDecimal kpifact) {
        this.kpifact = kpifact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.paidInAmount
     *
     * @return the value of departments.paidInAmount
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public BigDecimal getPaidinamount() {
        return paidinamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.paidInAmount
     *
     * @param paidinamount the value for departments.paidInAmount
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setPaidinamount(BigDecimal paidinamount) {
        this.paidinamount = paidinamount;
    }
}