package com.xuchen.domain;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.employeeId
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private Integer employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.employeeName
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private String employeename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.workYears
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private Integer workyears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.departmentId
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    private Integer departmentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.employeeId
     *
     * @return the value of employees.employeeId
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.employeeId
     *
     * @param employeeid the value for employees.employeeId
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.employeeName
     *
     * @return the value of employees.employeeName
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public String getEmployeename() {
        return employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.employeeName
     *
     * @param employeename the value for employees.employeeName
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setEmployeename(String employeename) {
        this.employeename = employeename == null ? null : employeename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.workYears
     *
     * @return the value of employees.workYears
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public Integer getWorkyears() {
        return workyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.workYears
     *
     * @param workyears the value for employees.workYears
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setWorkyears(Integer workyears) {
        this.workyears = workyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.departmentId
     *
     * @return the value of employees.departmentId
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.departmentId
     *
     * @param departmentid the value for employees.departmentId
     *
     * @mbg.generated Sun Aug 01 00:14:07 CST 2021
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }
}